#############################################################################
# Makefile for building: dynlab
# Generated by qmake (2.01a) (Qt 4.7.4) on: Mon Feb 6 15:44:49 2012
# Project:  dynlab.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile dynlab.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I$(AMDAPPSDKROOT)/include
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L$(AMDAPPSDKROOT)/lib/x86_64 -L/usr/lib/fglrx -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib64 -lOpenCL -lGLEW -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = fileinterface/colladainterface.cc \
		fileinterface/tinyxml.cpp \
		fileinterface/tinyxmlerror.cpp \
		fileinterface/tinystr.cpp \
		fileinterface/tinyxmlparser.cpp \
		componenteditor/glwidget.cc \
		componenteditor/glbase.cc \
		navigator/navigator.cc \
		mainwindow.cc \
		componenteditor/tabeditor.cc \
		propertybrowser/propertybrowser.cpp \
		propertybrowser/qteditorfactory.cpp \
		propertybrowser/qtpropertybrowser.cpp \
		propertybrowser/qtpropertybrowserutils.cpp \
		propertybrowser/qtpropertymanager.cpp \
		propertybrowser/qttreepropertybrowser.cpp \
		main.cc moc_glbase.cpp \
		moc_navigator.cpp \
		moc_mainwindow.cpp \
		moc_glwidget.cpp \
		moc_tabeditor.cpp \
		moc_propertybrowser.cpp \
		moc_qtpropertybrowserutils_p.cpp
OBJECTS       = colladainterface.o \
		tinyxml.o \
		tinyxmlerror.o \
		tinystr.o \
		tinyxmlparser.o \
		glwidget.o \
		glbase.o \
		navigator.o \
		mainwindow.o \
		tabeditor.o \
		propertybrowser.o \
		qteditorfactory.o \
		qtpropertybrowser.o \
		qtpropertybrowserutils.o \
		qtpropertymanager.o \
		qttreepropertybrowser.o \
		main.o \
		moc_glbase.o \
		moc_navigator.o \
		moc_mainwindow.o \
		moc_glwidget.o \
		moc_tabeditor.o \
		moc_propertybrowser.o \
		moc_qtpropertybrowserutils_p.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		dynlab.pro
QMAKE_TARGET  = dynlab
DESTDIR       = 
TARGET        = dynlab

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: dynlab.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile dynlab.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile dynlab.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/dynlab1.0.0 || $(MKDIR) .tmp/dynlab1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/dynlab1.0.0/ && $(COPY_FILE) --parents spheredata.h fileinterface/colladainterface.h fileinterface/tinyxml.h fileinterface/tinystr.h componenteditor/glbase.h navigator/navigator.h mainwindow.h componenteditor/glwidget.h componenteditor/tabeditor.h propertybrowser/propertybrowser.h propertybrowser/qteditorfactory.h propertybrowser/qtpropertybrowser.h propertybrowser/qtpropertybrowserutils_p.h propertybrowser/qtpropertymanager.h propertybrowser/qttreepropertybrowser.h .tmp/dynlab1.0.0/ && $(COPY_FILE) --parents fileinterface/colladainterface.cc fileinterface/tinyxml.cpp fileinterface/tinyxmlerror.cpp fileinterface/tinystr.cpp fileinterface/tinyxmlparser.cpp componenteditor/glwidget.cc componenteditor/glbase.cc navigator/navigator.cc mainwindow.cc componenteditor/tabeditor.cc propertybrowser/propertybrowser.cpp propertybrowser/qteditorfactory.cpp propertybrowser/qtpropertybrowser.cpp propertybrowser/qtpropertybrowserutils.cpp propertybrowser/qtpropertymanager.cpp propertybrowser/qttreepropertybrowser.cpp main.cc .tmp/dynlab1.0.0/ && (cd `dirname .tmp/dynlab1.0.0` && $(TAR) dynlab1.0.0.tar dynlab1.0.0 && $(COMPRESS) dynlab1.0.0.tar) && $(MOVE) `dirname .tmp/dynlab1.0.0`/dynlab1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/dynlab1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_glbase.cpp moc_navigator.cpp moc_mainwindow.cpp moc_glwidget.cpp moc_tabeditor.cpp moc_propertybrowser.cpp moc_qteditorfactory.cpp moc_qtpropertybrowser.cpp moc_qtpropertybrowserutils_p.cpp moc_qtpropertymanager.cpp moc_qttreepropertybrowser.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_glbase.cpp moc_navigator.cpp moc_mainwindow.cpp moc_glwidget.cpp moc_tabeditor.cpp moc_propertybrowser.cpp moc_qteditorfactory.cpp moc_qtpropertybrowser.cpp moc_qtpropertybrowserutils_p.cpp moc_qtpropertymanager.cpp moc_qttreepropertybrowser.cpp
moc_glbase.cpp: componenteditor/glwidget.h \
		mainwindow.h \
		componenteditor/tabeditor.h \
		navigator/navigator.h \
		propertybrowser/propertybrowser.h \
		propertybrowser/qtpropertymanager.h \
		propertybrowser/qtpropertybrowser.h \
		propertybrowser/qteditorfactory.h \
		propertybrowser/qttreepropertybrowser.h \
		spheredata.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/type_ptr.inl \
		fileinterface/colladainterface.h \
		fileinterface/tinyxml.h \
		fileinterface/tinystr.h \
		componenteditor/glbase.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) componenteditor/glbase.h -o moc_glbase.cpp

moc_navigator.cpp: navigator/navigator.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) navigator/navigator.h -o moc_navigator.cpp

moc_mainwindow.cpp: componenteditor/tabeditor.h \
		navigator/navigator.h \
		propertybrowser/propertybrowser.h \
		propertybrowser/qtpropertymanager.h \
		propertybrowser/qtpropertybrowser.h \
		propertybrowser/qteditorfactory.h \
		propertybrowser/qttreepropertybrowser.h \
		spheredata.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/type_ptr.inl \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_glwidget.cpp: mainwindow.h \
		componenteditor/tabeditor.h \
		navigator/navigator.h \
		propertybrowser/propertybrowser.h \
		propertybrowser/qtpropertymanager.h \
		propertybrowser/qtpropertybrowser.h \
		propertybrowser/qteditorfactory.h \
		propertybrowser/qttreepropertybrowser.h \
		spheredata.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/type_ptr.inl \
		fileinterface/colladainterface.h \
		fileinterface/tinyxml.h \
		fileinterface/tinystr.h \
		componenteditor/glwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) componenteditor/glwidget.h -o moc_glwidget.cpp

moc_tabeditor.cpp: componenteditor/tabeditor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) componenteditor/tabeditor.h -o moc_tabeditor.cpp

moc_propertybrowser.cpp: propertybrowser/qtpropertymanager.h \
		propertybrowser/qtpropertybrowser.h \
		propertybrowser/qteditorfactory.h \
		propertybrowser/qttreepropertybrowser.h \
		spheredata.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/type_ptr.inl \
		propertybrowser/propertybrowser.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) propertybrowser/propertybrowser.h -o moc_propertybrowser.cpp

moc_qteditorfactory.cpp: propertybrowser/qtpropertymanager.h \
		propertybrowser/qtpropertybrowser.h \
		propertybrowser/qteditorfactory.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) propertybrowser/qteditorfactory.h -o moc_qteditorfactory.cpp

moc_qtpropertybrowser.cpp: propertybrowser/qtpropertybrowser.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) propertybrowser/qtpropertybrowser.h -o moc_qtpropertybrowser.cpp

moc_qtpropertybrowserutils_p.cpp: propertybrowser/qtpropertybrowserutils_p.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) propertybrowser/qtpropertybrowserutils_p.h -o moc_qtpropertybrowserutils_p.cpp

moc_qtpropertymanager.cpp: propertybrowser/qtpropertybrowser.h \
		propertybrowser/qtpropertymanager.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) propertybrowser/qtpropertymanager.h -o moc_qtpropertymanager.cpp

moc_qttreepropertybrowser.cpp: propertybrowser/qtpropertybrowser.h \
		propertybrowser/qttreepropertybrowser.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) propertybrowser/qttreepropertybrowser.h -o moc_qttreepropertybrowser.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all: qteditorfactory.moc qtpropertymanager.moc qttreepropertybrowser.moc
compiler_moc_source_clean:
	-$(DEL_FILE) qteditorfactory.moc qtpropertymanager.moc qttreepropertybrowser.moc
qteditorfactory.moc: propertybrowser/qteditorfactory.h \
		propertybrowser/qtpropertymanager.h \
		propertybrowser/qtpropertybrowser.h \
		propertybrowser/qtpropertybrowserutils_p.h \
		moc_qteditorfactory.cpp \
		propertybrowser/qteditorfactory.cpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) propertybrowser/qteditorfactory.cpp -o qteditorfactory.moc

qtpropertymanager.moc: propertybrowser/qtpropertymanager.h \
		propertybrowser/qtpropertybrowser.h \
		propertybrowser/qtpropertybrowserutils_p.h \
		moc_qtpropertymanager.cpp \
		propertybrowser/qtpropertymanager.cpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) propertybrowser/qtpropertymanager.cpp -o qtpropertymanager.moc

qttreepropertybrowser.moc: propertybrowser/qttreepropertybrowser.h \
		propertybrowser/qtpropertybrowser.h \
		moc_qttreepropertybrowser.cpp \
		propertybrowser/qttreepropertybrowser.cpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) propertybrowser/qttreepropertybrowser.cpp -o qttreepropertybrowser.moc

compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_moc_source_clean 

####### Compile

colladainterface.o: fileinterface/colladainterface.cc fileinterface/colladainterface.h \
		fileinterface/tinyxml.h \
		fileinterface/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colladainterface.o fileinterface/colladainterface.cc

tinyxml.o: fileinterface/tinyxml.cpp fileinterface/tinyxml.h \
		fileinterface/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinyxml.o fileinterface/tinyxml.cpp

tinyxmlerror.o: fileinterface/tinyxmlerror.cpp fileinterface/tinyxml.h \
		fileinterface/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinyxmlerror.o fileinterface/tinyxmlerror.cpp

tinystr.o: fileinterface/tinystr.cpp fileinterface/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinystr.o fileinterface/tinystr.cpp

tinyxmlparser.o: fileinterface/tinyxmlparser.cpp fileinterface/tinyxml.h \
		fileinterface/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinyxmlparser.o fileinterface/tinyxmlparser.cpp

glwidget.o: componenteditor/glwidget.cc componenteditor/glwidget.h \
		mainwindow.h \
		componenteditor/tabeditor.h \
		navigator/navigator.h \
		propertybrowser/propertybrowser.h \
		propertybrowser/qtpropertymanager.h \
		propertybrowser/qtpropertybrowser.h \
		propertybrowser/qteditorfactory.h \
		propertybrowser/qttreepropertybrowser.h \
		spheredata.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/type_ptr.inl \
		fileinterface/colladainterface.h \
		fileinterface/tinyxml.h \
		fileinterface/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o componenteditor/glwidget.cc

glbase.o: componenteditor/glbase.cc componenteditor/glbase.h \
		componenteditor/glwidget.h \
		mainwindow.h \
		componenteditor/tabeditor.h \
		navigator/navigator.h \
		propertybrowser/propertybrowser.h \
		propertybrowser/qtpropertymanager.h \
		propertybrowser/qtpropertybrowser.h \
		propertybrowser/qteditorfactory.h \
		propertybrowser/qttreepropertybrowser.h \
		spheredata.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/type_ptr.inl \
		fileinterface/colladainterface.h \
		fileinterface/tinyxml.h \
		fileinterface/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glbase.o componenteditor/glbase.cc

navigator.o: navigator/navigator.cc navigator/navigator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o navigator.o navigator/navigator.cc

mainwindow.o: mainwindow.cc mainwindow.h \
		componenteditor/tabeditor.h \
		navigator/navigator.h \
		propertybrowser/propertybrowser.h \
		propertybrowser/qtpropertymanager.h \
		propertybrowser/qtpropertybrowser.h \
		propertybrowser/qteditorfactory.h \
		propertybrowser/qttreepropertybrowser.h \
		spheredata.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cc

tabeditor.o: componenteditor/tabeditor.cc componenteditor/tabeditor.h \
		componenteditor/glbase.h \
		componenteditor/glwidget.h \
		mainwindow.h \
		navigator/navigator.h \
		propertybrowser/propertybrowser.h \
		propertybrowser/qtpropertymanager.h \
		propertybrowser/qtpropertybrowser.h \
		propertybrowser/qteditorfactory.h \
		propertybrowser/qttreepropertybrowser.h \
		spheredata.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/type_ptr.inl \
		fileinterface/colladainterface.h \
		fileinterface/tinyxml.h \
		fileinterface/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tabeditor.o componenteditor/tabeditor.cc

propertybrowser.o: propertybrowser/propertybrowser.cpp propertybrowser/propertybrowser.h \
		propertybrowser/qtpropertymanager.h \
		propertybrowser/qtpropertybrowser.h \
		propertybrowser/qteditorfactory.h \
		propertybrowser/qttreepropertybrowser.h \
		spheredata.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o propertybrowser.o propertybrowser/propertybrowser.cpp

qteditorfactory.o: propertybrowser/qteditorfactory.cpp propertybrowser/qteditorfactory.h \
		propertybrowser/qtpropertymanager.h \
		propertybrowser/qtpropertybrowser.h \
		propertybrowser/qtpropertybrowserutils_p.h \
		moc_qteditorfactory.cpp \
		qteditorfactory.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qteditorfactory.o propertybrowser/qteditorfactory.cpp

qtpropertybrowser.o: propertybrowser/qtpropertybrowser.cpp propertybrowser/qtpropertybrowser.h \
		moc_qtpropertybrowser.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtpropertybrowser.o propertybrowser/qtpropertybrowser.cpp

qtpropertybrowserutils.o: propertybrowser/qtpropertybrowserutils.cpp propertybrowser/qtpropertybrowserutils_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtpropertybrowserutils.o propertybrowser/qtpropertybrowserutils.cpp

qtpropertymanager.o: propertybrowser/qtpropertymanager.cpp propertybrowser/qtpropertymanager.h \
		propertybrowser/qtpropertybrowser.h \
		propertybrowser/qtpropertybrowserutils_p.h \
		moc_qtpropertymanager.cpp \
		qtpropertymanager.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtpropertymanager.o propertybrowser/qtpropertymanager.cpp

qttreepropertybrowser.o: propertybrowser/qttreepropertybrowser.cpp propertybrowser/qttreepropertybrowser.h \
		propertybrowser/qtpropertybrowser.h \
		moc_qttreepropertybrowser.cpp \
		qttreepropertybrowser.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qttreepropertybrowser.o propertybrowser/qttreepropertybrowser.cpp

main.o: main.cc mainwindow.h \
		componenteditor/tabeditor.h \
		navigator/navigator.h \
		propertybrowser/propertybrowser.h \
		propertybrowser/qtpropertymanager.h \
		propertybrowser/qtpropertybrowser.h \
		propertybrowser/qteditorfactory.h \
		propertybrowser/qttreepropertybrowser.h \
		spheredata.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		glm/gtc/matrix_transform.hpp \
		glm/gtc/matrix_transform.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cc

moc_glbase.o: moc_glbase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glbase.o moc_glbase.cpp

moc_navigator.o: moc_navigator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_navigator.o moc_navigator.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

moc_tabeditor.o: moc_tabeditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tabeditor.o moc_tabeditor.cpp

moc_propertybrowser.o: moc_propertybrowser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_propertybrowser.o moc_propertybrowser.cpp

moc_qtpropertybrowserutils_p.o: moc_qtpropertybrowserutils_p.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtpropertybrowserutils_p.o moc_qtpropertybrowserutils_p.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./ || $(MKDIR) $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/home/mattscar/workspace/dynlab/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/home/mattscar/workspace/dynlab/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./ || $(MKDIR) $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./ 
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/fileinterface/colladainterface.cc $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/fileinterface/tinyxml.cpp $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/fileinterface/tinyxmlerror.cpp $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/fileinterface/tinystr.cpp $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/fileinterface/tinyxmlparser.cpp $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/componenteditor/glwidget.cc $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/componenteditor/glbase.cc $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/navigator/navigator.cc $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/mainwindow.cc $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/componenteditor/tabeditor.cc $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/propertybrowser/propertybrowser.cpp $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/propertybrowser/qteditorfactory.cpp $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/propertybrowser/qtpropertybrowser.cpp $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/propertybrowser/qtpropertybrowserutils.cpp $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/propertybrowser/qtpropertymanager.cpp $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/propertybrowser/qttreepropertybrowser.cpp $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/main.cc $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/spheredata.h $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/fileinterface/colladainterface.h $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/fileinterface/tinyxml.h $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/fileinterface/tinystr.h $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/componenteditor/glbase.h $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/navigator/navigator.h $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/mainwindow.h $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/componenteditor/glwidget.h $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/componenteditor/tabeditor.h $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/propertybrowser/propertybrowser.h $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/propertybrowser/qteditorfactory.h $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/propertybrowser/qtpropertybrowser.h $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/propertybrowser/qtpropertybrowserutils_p.h $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/propertybrowser/qtpropertymanager.h $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/propertybrowser/qttreepropertybrowser.h $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./
	-$(INSTALL_PROGRAM) /home/mattscar/workspace/dynlab/dynlab.pro $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./colladainterface.cc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./tinyxml.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./tinyxmlerror.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./tinystr.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./tinyxmlparser.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./glwidget.cc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./glbase.cc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./navigator.cc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./mainwindow.cc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./tabeditor.cc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./propertybrowser.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./qteditorfactory.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./qtpropertybrowser.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./qtpropertybrowserutils.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./qtpropertymanager.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./qttreepropertybrowser.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./main.cc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./spheredata.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./colladainterface.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./tinyxml.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./tinystr.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./glbase.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./navigator.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./mainwindow.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./glwidget.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./tabeditor.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./propertybrowser.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./qteditorfactory.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./qtpropertybrowser.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./qtpropertybrowserutils_p.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./qtpropertymanager.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./qttreepropertybrowser.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./dynlab.pro
	-$(DEL_DIR) $(INSTALL_ROOT)/home/mattscar/workspace/dynlab/./ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

